set_property PACKAGE_PIN L16 [get_ports seri_clk_p]
set_property PACKAGE_PIN K17 [get_ports seri_b_p]
set_property PACKAGE_PIN K19 [get_ports seri_g_p]
set_property PACKAGE_PIN J18 [get_ports seri_r_p]
set_property PACKAGE_PIN D19 [get_ports reset]
set_property PACKAGE_PIN R14 [get_ports led[0]]
set_property PACKAGE_PIN P14 [get_ports led[1]]
set_property PACKAGE_PIN N16 [get_ports led[2]]
set_property PACKAGE_PIN M14 [get_ports led[3]]
set_property PACKAGE_PIN D20 [get_ports btn[0]]
set_property PACKAGE_PIN L20 [get_ports btn[1]]
set_property PACKAGE_PIN L19 [get_ports btn[2]]
set_property PACKAGE_PIN M20 [get_ports sw[0]]
set_property PACKAGE_PIN M19 [get_ports sw[1]]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports btn]
set_property IOSTANDARD LVCMOS33 [get_ports sw]


set_property DRIVE 4 [get_ports led[0]]
set_property DRIVE 4 [get_ports led[1]]
set_property DRIVE 4 [get_ports led[2]]
set_property DRIVE 4 [get_ports led[3]]
